feat: add the ability to delete a user and a movie by ID
LLaym/java-filmorate pull request #14
Opened 2023-05-23 11:10 UTC by EugeneStartsev

2023-05-23 16:40 UTC, LLaym approved these changes
Все супер! Не совсем понимаю только зачем возвращается объект фильма/пользователя при удалении. Approve

2023-05-23 16:40 UTC, LLaym commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Optional<User> deleteById(int userId);
Интересно, почему при удалении возвращается Optional а не какой нибудь boolean? Наверное в этом есть смысл)

2023-05-23 17:27 UTC, Blinnik commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        Optional<Film> film = jdbcTemplate.query(getByIdSql, ((rs, rowNum) -> makeFilm(rs)), filmId)
Плюсую Виталию) Не понимаю зачем возвращать Optional/Film при удалении. Делаешь два запроса вместо одного. Также, если посмотреть, например, на FriendshipDbStorage / UserService, там уже была реализована подобная функция удаления объекта из БД. И в этих методах возвращался boolean. Я думаю, лучше исправить это в методах, чтобы все было в одном стиле

2023-05-23 17:28 UTC, julsa006 requested changes

2023-05-23 17:28 UTC, julsa006 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .orElseThrow(() -> new FilmNotFoundException("Фильм с id " + filmId + " не найден"));
В контроллере валидатором уже проверяется существование фильма.

2023-05-23 17:28 UTC, julsa006 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .orElseThrow(() -> new UserNotFoundException("Пользователь с id " + userId + " не найден"));
Тоже существование уже проверилось в контроллере.

2023-05-23 17:28 UTC, julsa006 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        Optional<Film> film = jdbcTemplate.query(getByIdSql, ((rs, rowNum) -> makeFilm(rs)), filmId)
Можно переиспользовать уже существующий метод getById

2023-05-23 17:28 UTC, julsa006 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +        Optional<User> user = jdbcTemplate.query(getByIdSql, ((rs, rowNum) -> makeUser(rs)), userId)
Аналогично, можно переиспользовать уже существующий метод getById

2023-05-27 15:53 UTC, Blinnik approved these changes

2023-05-27 16:32 UTC, julsa006 approved these changes

2023-05-27 22:06 UTC, merged