Рабочий вариант простейшего API
LLaym/java-filmorate pull request #2
Opened 2023-03-17 18:02 UTC by LLaym

2023-03-18 16:04 UTC, VertigoMaker requested changes
Хорошая работа

2023-03-18 16:04 UTC, VertigoMaker commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String description;
Здесь можно использовать @Size(min = 1, max = 200)

2023-03-18 17:15 UTC, LLaym commented
Не понимаю почему не проходит тест после коммита. 
![изображение](https://user-images.githubusercontent.com/113213520/226122551-a901b099-eeef-47ef-9431-2a831cd61963.png)

2023-03-18 17:45 UTC, LLaym commented
> Не понимаю почему не проходит тест после коммита. ![изображение](https://user-images.githubusercontent.com/113213520/226122551-a901b099-eeef-47ef-9431-2a831cd61963.png)

Исправил удалением .mvn каталога

2023-03-19 14:53 UTC, VertigoMaker approved these changes
Теперь всё верно!

2023-03-19 15:46 UTC, merged